In [1]:
import numpy as np
from numpy.random import randint, rand, shuffle
from matplotlib.pyplot import plot ,show ,rc

In [2]:
a = np.loadtxt("Pdata17_2.txt")

In [3]:
xy, d = a[:, :2], a[:,2]

In [4]:
xy, d

(array([[7.00000e+01, 4.00000e+01],
        [5.37121e+01, 1.53046e+01],
        [5.11758e+01, 3.22000e-02],
        [4.63253e+01, 2.82753e+01],
        [3.03313e+01, 6.93480e+00],
        [5.65432e+01, 2.14188e+01],
        [1.08198e+01, 1.62529e+01],
        [2.27891e+01, 2.31045e+01],
        [1.01584e+01, 1.24819e+01],
        [2.01050e+01, 1.54562e+01],
        [1.94510e+00, 2.05700e-01],
        [2.64951e+01, 2.21221e+01],
        [3.14847e+01, 8.96400e+00],
        [2.62418e+01, 1.81760e+01],
        [4.40356e+01, 1.35401e+01],
        [2.89836e+01, 2.59879e+01],
        [3.84722e+01, 2.01731e+01],
        [2.82694e+01, 2.90011e+01],
        [3.21910e+01, 5.86990e+00],
        [3.64863e+01, 2.97284e+01],
        [9.71800e-01, 2.81477e+01],
        [8.95860e+00, 2.46635e+01],
        [1.65618e+01, 2.36143e+01],
        [1.05597e+01, 1.51178e+01],
        [5.02111e+01, 1.02944e+01],
        [8.15190e+00, 9.53250e+00],
        [2.21075e+01, 1.85569e+01],
        [1.21500e-01, 1.8872

In [5]:
N = len(xy)
w = 50
g = 10 # w为种群的个数，g为进化的代数
J = []

In [7]:
xl = np.zeros(10)
xl[0] = -5.0

In [9]:
xl

array([-5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [15]:
L = np.array([np.random.randint(100) for _ in range(100)])

In [16]:
L

array([60, 59, 29,  2, 78, 51,  3,  0, 10,  2, 41, 81, 47, 11, 18, 67, 50,
       22, 75, 78, 15, 76, 49, 98, 82, 24, 97, 85, 60, 92, 45, 79, 37,  2,
       20, 84, 72, 34,  2, 59, 93, 97, 41, 66, 43,  6, 60, 24,  9, 93, 28,
        9, 48, 81, 99, 43,  7, 50, 71, 80, 40, 99, 14, 45, 62, 62, 15, 46,
       13, 25, 73,  1, 78, 59, 10, 45, 78, 55, 15, 81, 45, 84, 16, 44, 76,
       52, 87, 19, 90, 10,  3, 64, 23, 73, 74, 31, 35, 93, 30, 89])

In [17]:
b = sum(range(0,10))

In [18]:
b

45

In [23]:
L1 = np.array([np.random.randint(5) for _ in range(5)])

In [24]:
L1

array([3, 4, 2, 4, 0])

In [28]:
X = np.array([True,True, True, False, True])

In [29]:
np.sum(L1[X])

9